{
 "title": "Воздух",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kg_pollutant",
    "label": "Загрязнитель (Казгидромет)",
    "query": "SO2,NO2,NO,PM2.5,CO,H2S,PM10,PMtot"
   },
   {
    "name": "ceb_pollutant",
    "label": "Загрязнитель (ЦЭБ)",
    "query": "SO2,NO2,HF,HCL,CL2, CO, CXHY, HCOH,"
   }
  ]
 },
 "panels": [
  {
   "title": "Воздух в помещении",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"particulates\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ug_atm_2_5\")\n  |> filter(fn: (r) => r[\"device\"] == \"bedroom\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"co2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\n  |> filter(fn: (r) => r[\"device\"] == \"bedroom_co2\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM₂₅ на лоджии, мкг/м³",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"particulates\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ug_atm_2_5\")\n  |> filter(fn: (r) => r[\"device\"] == \"balcony\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PM₂₅ на улице, мкг/м³",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"airkaz:particulates\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm25\")\n  |> filter(fn: (r) => r[\"city\"] == \"Усть-Каменогорск\")\n  |> group(columns: [\"station\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SO₂",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kazhydromet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"city\"] == \"Усть-Каменогорск\")\n  |> filter(fn: (r) => r[\"code\"] == \"SO2\")\n  |> map(fn: (r) => ({\n    r with\n    _value: r._value * 1000.0\n  })\n)\n  |> group(columns: [\"address\"])\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false) "
    },
    {
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ceb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level_ug\")\n  |> filter(fn: (r) => r[\"formula\"] == \"SO2\")\n  |> filter(fn: (r) => r._value > 0)\n  |> group(columns: [\"address\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "$ceb_pollutant (ЦЭБ), мкг/м³",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "ceb_pollutant",
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ceb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"level_ug\")\n  |> filter(fn: (r) => r[\"formula\"] == \"$ceb_pollutant\")\n  |> filter(fn: (r) => r._value > 0)\n  |> group(columns: [\"address\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Казгидромет", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "$kg_pollutant (Казгидромет), мкг/м³",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 91 },
   "repeat": "kg_pollutant",
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kazhydromet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"city\"] == \"Усть-Каменогорск\")\n  |> filter(fn: (r) => r[\"code\"] == \"$kg_pollutant\")\n  |> map(fn: (r) => ({\n    r with\n    _value: r._value * 1000.0\n  })\n)\n  |> group(columns: [\"address\"])\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Скорость ветра, м/с",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kazhydromet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"city\"] == \"Усть-Каменогорск\")\n  |> filter(fn: (r) => r[\"code\"] == \"WS\")\n  |> group(columns: [\"address\"])\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Температура воздуха, °C",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kazhydromet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"city\"] == \"Усть-Каменогорск\")\n  |> filter(fn: (r) => r[\"code\"] == \"AT\")\n  |> group(columns: [\"address\"])\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "airkaz",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM₂₅ по городам",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "conμgm3" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"airkaz:particulates\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm25\")\n  |> group(columns: [\"city\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DIY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM₂₅ в помещении, мкг/м³",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "conμgm3" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"particulates\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ug_atm_2_5\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CO₂ в помещении, PPM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "ppm" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"co2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\n  |> filter(fn: (r) => r[\"device\"] == \"bedroom_co2\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Температура",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"airmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}